### ISSUE TITLE
Add <editor-input>

### ISSUE THREAD

**Issue by jwu** [fireball-packages/ui-kit#6]
editor-input is a wrapper of [iron-input](https://elements.polymer-project.org/elements/iron-input)

 - [x] Basic function for <editor-input>
 - [x] A style guide for it, reference: http://semantic-ui.com/elements/input.html
 - [x] tests

**Comment by w88975** [comment]
styleguid:
- [ ] 1.size
- [ ] 2.validator style
- [ ] 3.disabled
- [ ] 4.placeholder
