### ISSUE TITLE
tweak the styles of <editor-button>

### ISSUE THREAD

**Issue by jwu** [fireball-packages/ui-kit#7]
Tweak step:

 1. Open Package Studio
 1. Open Panel/UI Kit Preview
 1. edit builtin/ui-kit/widget/button/button.less
 1. refresh and confirm your tweak

If anything changes relative with root element (rem), you should add css properties in `editor-framework/page/ui/common.css`, please discuss with @jwu for any of changes in common.css

**Comment by jwu** [comment]
my suggestion:

 - color button needs tweak
 - button size not respond with margin

**Comment by nantas** [comment]
中文任务描述：

使用统一风格的样式指导，对 UI Kit 中的 button 做设计上的调整
